parserOptions:
  ecmaVersion: latest
env:
  es6: true
rules:
  array-bracket-spacing: [error, always]
  comma-dangle: [error, always-multiline]
  comma-spacing: error
  eol-last: [error, always]
  eqeqeq: error
  no-var: error
  object-curly-spacing: [error, always]
  quotes:
    - error
    - single
    - { avoidEscape: true }
  semi: [error, never]
