compilerOptions:
  outDir: lib
  noEmit: false
  declaration: true
  sourceMap: true
  noEmitOnError: true
  stripInternal: true
  target: ES2022
  module: esnext
  moduleResolution: node
  strict: true
  esModuleInterop: true
  resolveJsonModule: true
  isolatedModules: true
  typeRoots:
    - node_modules/@types
    - types
include: 
  - src
  - types
  - test
# `exclude: node_modules` would work if typescript supported YAML.
# The JSON conversion needs an explicit array.
exclude: [node_modules]
